import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms — DevReview",
  description:
    "Terms and conditions for using DevReview, the AI code-review service.",
};

const UPDATED = "30 May 2026";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0D0D0D] text-[#F8F8F2] font-mono text-[13px] leading-[1.7]">
      <div className="mx-auto max-w-[760px] px-6 py-12">
        <Link
          href="/"
          className="text-[#6C7280] text-[11.5px] hover:text-[#F8F8F2] no-underline"
        >
          ← back to dev·review
        </Link>

        <h1 className="mt-6 text-[20px] font-semibold text-[#F8F8F2]">
          Terms &amp; Conditions
        </h1>
        <p className="mt-1 text-[#6C7280] text-[11.5px]">
          Last updated: {UPDATED}
        </p>

        <p className="mt-6 text-[#C8CCD2]">
          DevReview is a code-review tool operated by Andre Sha (ABN{" "}
          <Em>53 858 093 095</Em>), a sole trader based in Victoria, Australia
          (&quot;DevReview&quot;, &quot;we&quot;, &quot;us&quot;). These terms
          govern your use of the website and service. By using DevReview —
          anonymously or signed in — you agree to them. If you don&apos;t agree,
          don&apos;t use the service.
        </p>

        <Section title="The short version">
          <ul className="list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>
              The review is generated by an AI model. It can be wrong, miss
              problems, or invent issues. <Em>Verify everything yourself</Em> —
              it is not professional, security, or legal advice.
            </li>
            <li>
              Only submit code you have the right to submit, and never paste
              secrets, credentials, or other people&apos;s personal data.
            </li>
            <li>
              You keep all rights to the code you submit. We claim no ownership
              and don&apos;t use it to train anything.
            </li>
            <li>
              Paid plans bill through <Em>Stripe</Em> on a recurring basis until
              you cancel. You can cancel anytime; access runs to the end of the
              paid period.
            </li>
            <li>
              The service is provided &quot;as is&quot;, with no uptime or
              accuracy guarantee — but nothing here removes rights you have
              under the Australian Consumer Law.
            </li>
            <li>
              Don&apos;t abuse the service: no circumventing quotas, scraping,
              reselling, or using it for anything unlawful.
            </li>
          </ul>
        </Section>

        <Section title="Who can use DevReview">
          <p className="text-[#C8CCD2]">
            You must be able to form a binding contract to use DevReview. If you
            create an account or subscribe to a paid plan, you confirm you are
            at least 18 years old. If you use DevReview on behalf of an
            organisation, you confirm you are authorised to bind that
            organisation to these terms.
          </p>
        </Section>

        <Section title="What the service does — and what it doesn't">
          <p className="text-[#C8CCD2]">
            You paste a code snippet or point DevReview at a GitHub pull
            request, and it returns an AI-generated review highlighting possible
            security, performance, and style issues. That output is{" "}
            <Em>informational only</Em>. It is produced by a third-party
            language model and:
          </p>
          <ul className="mt-3 list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>may be inaccurate, incomplete, or out of date;</li>
            <li>
              may miss real defects or vulnerabilities, or flag issues that
              don&apos;t exist;
            </li>
            <li>
              is <Em>not</Em> a substitute for professional code audit, security
              testing, or legal, financial, or other professional advice.
            </li>
          </ul>
          <p className="mt-3 text-[#C8CCD2]">
            You are responsible for independently reviewing and testing any code
            before relying on it. Do not treat a DevReview result as the sole
            basis for shipping, securing, or relying on code.
          </p>
        </Section>

        <Section title="Your content and your responsibilities">
          <p className="text-[#C8CCD2]">
            &quot;Your content&quot; means the code, diffs, pull-request
            references, and tokens you submit. When you submit it, you confirm
            that:
          </p>
          <ul className="mt-3 list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>
              you own it or have the right to submit it and to have it processed
              as described in our{" "}
              <Link href="/privacy" className="underline hover:text-[#F8F8F2]">
                Privacy Policy
              </Link>
              ;
            </li>
            <li>
              submitting it does not breach any employer policy, licence,
              confidentiality obligation, or law;
            </li>
            <li>
              it contains no secrets, API keys, passwords, or personal
              information about other people that you are not authorised to
              share;
            </li>
            <li>
              you understand it will be sent to Anthropic to generate the
              review, and (for pull requests) that the PR reference and any
              token you supply will be sent to GitHub.
            </li>
          </ul>
          <p className="mt-3 text-[#C8CCD2]">
            You keep all intellectual property rights in your content. You grant
            us only the limited licence needed to receive, process, and transmit
            it to the model providers in order to produce your review for that
            request. We do not sell your content, and we do not use it to train
            any model. We do not store the code or the review text — see the{" "}
            <Link href="/privacy" className="underline hover:text-[#F8F8F2]">
              Privacy Policy
            </Link>{" "}
            for exactly what is and isn&apos;t kept.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p className="text-[#C8CCD2]">You agree not to:</p>
          <ul className="mt-3 list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>
              circumvent, disable, or interfere with rate limits, quotas, or
              usage metering;
            </li>
            <li>
              resell, sublicense, or commercially redistribute the service or
              its output without our written permission;
            </li>
            <li>
              use automated means to scrape the service, or use it to build a
              competing product or dataset;
            </li>
            <li>
              submit content that is unlawful, infringing, malicious (e.g.
              malware), or that you are not authorised to share;
            </li>
            <li>
              attempt to gain unauthorised access to the service, other
              users&apos; accounts, or our infrastructure, or otherwise probe,
              overload, or disrupt it.
            </li>
          </ul>
          <p className="mt-3 text-[#C8CCD2]">
            We may apply rate limits and quotas, and may suspend or restrict
            access if we reasonably believe you have breached these terms.
          </p>
        </Section>

        <Section title="Accounts">
          <p className="text-[#C8CCD2]">
            Anonymous use needs no account. To subscribe to a paid plan you sign
            in with Google or GitHub. You are responsible for activity under
            your account and for keeping your provider login secure. Provide
            accurate information, use one account per person, and tell us
            promptly if you suspect unauthorised use. You can delete your
            account at any time from the Account page.
          </p>
        </Section>

        <Section title="Plans, fees, and billing">
          <p className="text-[#C8CCD2]">
            DevReview offers a free tier with usage quotas and paid plans (Lite
            and Pro). Current features, quotas, and prices are shown on the{" "}
            <Link href="/#pricing" className="underline hover:text-[#F8F8F2]">
              pricing page
            </Link>{" "}
            and form part of these terms. By subscribing you authorise us,
            through our payment processor <Em>Stripe</Em>, to charge the
            applicable fee on a recurring basis (e.g. monthly) until you cancel.
          </p>
          <ul className="mt-3 list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>
              Subscriptions renew automatically at the start of each billing
              period unless cancelled beforehand.
            </li>
            <li>
              Payments are processed by Stripe. We do not see or store your full
              card details.
            </li>
            <li>
              Prices are in the currency shown at checkout and are exclusive of
              any applicable taxes unless stated otherwise. You are responsible
              for any taxes that apply to you.
            </li>
            <li>
              We may change plans, features, quotas, or prices. We will give
              reasonable notice of price changes affecting your current
              subscription, and changes take effect from your next billing
              period.
            </li>
          </ul>
        </Section>

        <Section title="Cancellation and refunds">
          <p className="text-[#C8CCD2]">
            You can cancel a paid plan at any time from the Account page.
            Cancellation stops future renewals; your plan stays active until the
            end of the period you&apos;ve already paid for, and we don&apos;t
            pro-rate or refund part-used periods for change of mind.
          </p>
          <p className="mt-3 text-[#C8CCD2]">
            This does not limit your rights under the Australian Consumer Law —
            see below. If a paid plan fails to meet a consumer guarantee, you
            may be entitled to a remedy regardless of this policy.
          </p>
        </Section>

        <Section title="Availability">
          <p className="text-[#C8CCD2]">
            DevReview is provided on an &quot;as is&quot; and &quot;as
            available&quot; basis. We don&apos;t guarantee that it will be
            uninterrupted, error-free, secure, or that reviews will be accurate
            or available at any given time. We may modify, suspend, or
            discontinue any part of the service, including features and plans,
            at any time. Because reviews depend on third-party providers
            (Anthropic, GitHub), outages or changes on their side may affect the
            service.
          </p>
        </Section>

        <Section title="Third-party services">
          <p className="text-[#C8CCD2]">
            DevReview relies on third parties — including Anthropic (model),
            GitHub and Google (sign-in / diffs), Stripe (payments), and Neon,
            Upstash, and Vercel (infrastructure). Your use of those services
            through DevReview is also governed by their own terms and privacy
            policies. We are not responsible for the acts, omissions, or
            availability of third-party providers.
          </p>
        </Section>

        <Section title="Australian Consumer Law">
          <p className="text-[#C8CCD2]">
            Our services come with guarantees that cannot be excluded under the
            Australian Consumer Law (ACL). Nothing in these terms excludes,
            restricts, or modifies any guarantee, right, or remedy you have
            under the ACL or any other law that cannot lawfully be excluded.
          </p>
          <p className="mt-3 text-[#C8CCD2]">
            Where we are permitted to limit our liability for breach of a
            non-excludable guarantee, our liability is limited, at our option,
            to resupplying the relevant service or paying the cost of having it
            resupplied.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p className="text-[#C8CCD2]">
            Subject to the <Em>Australian Consumer Law</Em> section above, and
            to the maximum extent permitted by law:
          </p>
          <ul className="mt-3 list-disc pl-5 space-y-1 text-[#C8CCD2]">
            <li>
              we are not liable for any indirect, incidental, special, or
              consequential loss, or for loss of profits, data, goodwill, or
              business, arising from your use of DevReview;
            </li>
            <li>
              we are not liable for any loss arising from your reliance on a
              review — including defects or vulnerabilities a review fails to
              identify, or issues it wrongly reports;
            </li>
            <li>
              our total aggregate liability arising out of or in connection with
              the service is limited to the greater of (a) the total fees you
              paid us in the 12 months before the event giving rise to the
              claim, or (b) AUD $100.
            </li>
          </ul>
        </Section>

        <Section title="Indemnity">
          <p className="text-[#C8CCD2]">
            To the extent permitted by law, you agree to indemnify us against
            claims, losses, and costs arising from your breach of these terms,
            your misuse of the service, or your submission of content you
            weren&apos;t authorised to submit (including any breach of a third
            party&apos;s intellectual property, confidentiality, or privacy
            rights).
          </p>
        </Section>

        <Section title="Suspension and termination">
          <p className="text-[#C8CCD2]">
            You can stop using DevReview at any time and delete your account. We
            may suspend or terminate your access if you breach these terms,
            misuse the service, or if we&apos;re required to by law. On
            termination, the sections that by their nature should survive —
            including content rights, disclaimers, liability limits, and
            indemnity — continue to apply.
          </p>
          <p className="mt-3 text-[#C8CCD2]">
            If you can&apos;t delete your account through the Account page — for
            example because of an outage at Stripe or our database — please
            contact us using the details below and we will action the deletion
            (including cancelling any active paid subscription) manually, as
            soon as reasonably practicable.
          </p>
        </Section>

        <Section title="Privacy">
          <p className="text-[#C8CCD2]">
            Our handling of what you submit and any account data is described in
            our{" "}
            <Link href="/privacy" className="underline hover:text-[#F8F8F2]">
              Privacy Policy
            </Link>
            , which forms part of these terms.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p className="text-[#C8CCD2]">
            We may update these terms from time to time. When we do, we&apos;ll
            change the &quot;last updated&quot; date above, and for material
            changes we&apos;ll take reasonable steps to let signed-in users
            know. Continuing to use DevReview after a change means you accept
            the updated terms.
          </p>
        </Section>

        <Section title="Governing law and contact">
          <p className="text-[#C8CCD2]">
            These terms are governed by the laws of Victoria, Australia, and you
            submit to the non-exclusive jurisdiction of its courts. Questions
            about these terms can be directed to <Em>andre@kohastudio.dev</Em>.
          </p>
        </Section>

        <p className="mt-10 text-[#4A4D54] text-[11px]">
          DevReview is operated as a commercial service by Andre Sha (sole
          trader), Victoria, Australia.
        </p>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8">
      <h2 className="text-[14px] font-semibold text-[#F8F8F2] lowercase tracking-[0.02em]">
        {title}
      </h2>
      <div className="mt-2">{children}</div>
    </section>
  );
}

function Em({ children }: { children: React.ReactNode }) {
  return <span className="text-[#F8F8F2] font-semibold">{children}</span>;
}
